### ISSUE TITLE
Not a bee_pack file

### ISSUE THREAD

**Issue by slambo312** [ErinRoseWebs/BEE2-Pixel-Styles#1]
You gotta compile a package, zip files don't work.

**Comment by ErinRoseWebs** [comment]
> You gotta compile a package, zip files don't work.

woah yo idk how u found this lol. its far from finished. and to answer, yes, you can use a .zip folder. in fact, thats what .bee_packs essentially are. they named it .bee_pack to discourage people from extracting their contents when they're not supposed to. you can try this yourself by naming a random package, say p1_style.bee_pack, to p1_style.zip. itll load up just fine.

**Comment by slambo312** [comment]
oh

**Comment by ErinRoseWebs** [comment]
> oh

one last thing before i close this issue; how did u find this repo? random searching?

**Comment by slambo312** [comment]
Yep. Just searching for bee2 addons and I found this.

**Comment by ErinRoseWebs** [comment]
huh. ighty.
